### ISSUE TITLE
Signature Verification

### ISSUE THREAD

**Issue by pebu1337** [ecies/py#254]
Hi there,
Currently trying to get signature verification working with an eth public/private key.
I was wondering if I could get some guidance on what is wrong with this?
I was using verify_signature as it was linked in a different issue regarding signatures.
```python
from ecies import generate_eth_key
from coincurve.keys import PrivateKey, PublicKey
from coincurve import verify_signature
privateKeyObject = generate_eth_key()
privateKey = str(privateKeyObject.to_hex())
publicKey = privateKeyObject.public_key
privateKeyObject = PrivateKey.from_hex(privateKey[2:])
msg = "test".encode()
sig = privateKeyObject.sign(msg)
print(msg)
print(sig)
print(publicKey)
bool = verify_signature(sig, msg, publicKey)
```
Output:
```python
b'test'
b'0E\x02!\x00\xf6\xfb\xfe\x1f\x84\xcc\xe0\x9d\xf1\x11\x01*P\xf5t\x8e(\xa0\x9b)V\xd6\xb6\xe5\xa8\xbf\xf9\xe0bq?\xfa\x02 *\xabWS\xba\x003U<>\xd2\x06}_\x84\xf1\xa5H](\xfe\xff_\'\x1b\xc6\x9f~0\xedD"'
0x46bf13ace911d1517d831c5096abcbea993f356055acc14e8984770310d0fc25c83c8a1f80a21f566d71565615e65b26ce692279fcab0563f7311b4b488575a5
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    bool = verify_signature(sig, msg, publicKey)
  File "/home/pebu/.local/lib/python3.8/site-packages/coincurve/utils.py", line 111, in verify_signature
    pubkey_parsed = lib.secp256k1_ec_pubkey_parse(context.ctx, pubkey, public_key, len(public_key))
TypeError: initializer for ctype 'unsigned char *' must be a cdata pointer, not PublicKey
```

**Comment by kigawas** [comment]
You can check coincurve's documentation: https://ofek.dev/coincurve/api/#coincurve.utils.verify_signature

The public key should be bytes, rather than `PublicKey`

**Comment by pebu1337** [comment]
```python
publicKey = bytes(privateKeyObject.public_key)
OverflowError: cannot fit 'PublicKey' into an index-sized integer
```

**Comment by kigawas** [comment]
> ```python
> publicKey = bytes(privateKeyObject.public_key)
> OverflowError: cannot fit 'PublicKey' into an index-sized integer
> ```

You can try `public_key.format()`

**Comment by pebu1337** [comment]
Figured it out, 
It just doesn't seem to work with generate_eth_key so I just switched to generate_key
Thanks!
