### ISSUE TITLE
Problem installing for python 3.13 running in Windows Server 2022

### ISSUE THREAD

**Issue by robinsonper** [ecies/py#378]
I'm having issues getting the library installed with pip, also tried downloading the wheel and running offline but keep getting the error below, I can't tell if this is related to the OS, my version of python or something else.
The environment specs are:
- Windows 2022 server 10.0
- Python 3.13.0
- PIP 24.3.1

```Collecting coincurve<21,>=13 (from eciespy==0.4.3)
  Using cached coincurve-20.0.0.tar.gz (122 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      WARNING: Use build.verbose instead of cmake.verbose for scikit-build-core >= 0.10
      *** scikit-build-core 0.10.7 using CMake 3.31.0 (wheel)
      *** Configuring CMake...
      loading initial cache file C:\Users\test_user\Temp\2\tmp4s7ul_6x\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory


      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Program Files\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Program Files\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
          build_hook.initialize(version, build_data)
          ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 124, in initialize
          self._initialize(build_data=build_data)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\scikit_build_core\hatch\plugin.py", line 226, in _initialize
          builder.configure(
          ~~~~~~~~~~~~~~~~~^
              defines=defines,
              ^^^^^^^^^^^^^^^^
          ...<2 lines>...
              version=Version(self.build_config.builder.metadata.version),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\scikit_build_core\builder\builder.py", line 255, in configure
          self.config.configure(
          ~~~~~~~~~~~~~~~~~~~~~^
              defines=cmake_defines,
              ^^^^^^^^^^^^^^^^^^^^^^
              cmake_args=[*self.get_cmake_args(), *configure_args],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "C:\Users\test_user\Temp\2\pip-build-env-hwy8111w\overlay\Lib\site-packages\scikit_build_core\cmake.py", line 242, in configure
          raise FailedLiveProcessError(msg) from None
      scikit_build_core.errors.FailedLiveProcessError: CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details```

**Comment by kigawas** [comment]
You need nmake to build coincurve

**Comment by kigawas** [comment]
The GitHub action build is also on windows server 2022

https://github.com/ecies/py/actions/runs/11781992102/job/32816032785

**Comment by robinsonper** [comment]
Thanks Kigawas, I'll try that.
